---
language:
  - generic
os: linux
dist: trusty
sudo: required
env:
  global:
    - APT_REPO="http://packages.ros.org/ros-shadow-fixed/ubuntu"
    - APT_MIRRORS="http://packages.ros.org/ros-shadow-fixed/ubuntu"
    - DEB_DISTRIBUTION="trusty"
    - TEMP_DEBS_DIR="/tmp/debs"
    - BINTRAY_REPOSITORY="furushchev/ros-shadow-fixed"
    - BINTRAY_USER=furushchev
    - MAX_PROCS=10
    - DL_CONCURRENT_NUM=5
    - DEB_DISTRIBUTION=`lsb_release -cs`
    - LOG_FILE="/tmp/log.txt"
before_script:
  - sudo sh -c "echo \"deb $APT_REPO $DEB_DISTRIBUTION main\" > /etc/apt/sources.list.d/ros-latest.list"
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y python-rosinstall-generator lsb-release sed grep gawk aptitude curl jq aria2
script:
  - ./build.sh
after_failure:
  - tail $LOG_FILE